### ISSUE TITLE
Failing to register error in the v48 update btd6

### ISSUE THREAD

**Issue by loks1234** [Void-n-Null/Banana-Farmer-Tower#8]
Tried to use this mod but after download the mod manager just says that "This mod has failed to register". Can you please update the mod to latest version. Thanks.

**Comment by loks1234** [comment]
Log from the melonloader window where it shows the error.:

[08:47:42.565] [BloonsTD6_Mod_Helper] Registering ModContent for BloonsTD6 Mod Helper...
[08:47:42.569] [BloonsTD6_Mod_Helper] Registering ModContent for Banana Farmer Tower...
[08:47:42.795] [BloonsTD6_Mod_Helper] Failed to ApplyUpgrade BananaBanker to TowerModel BananaFarmerTower-Banana Farmer-003
[08:47:42.796] [BloonsTD6_Mod_Helper] Failed to register BananaFarmerTower-Banana Farmer
[08:47:42.799] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Void Il2CppAssets.Scripts.Models.Towers.Behaviors.MonkeyCityIncomeSupportModel..ctor(System.String, Boolean, System.String, Single, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<Il2CppAssets.Scripts.Models.Towers.TowerFilters.TowerFilterModel>, System.String, System.String)'.
   at VoidBananaFarmer.Tower.Upgrades.BottomPathUpgrades.Tier3.ApplyUpgrade(TowerModel towerModel)
   at BTD_Mod_Helper.Api.Towers.ModTowerHelper.FinalizeTowerModel(ModTower modTower, TowerModel towerModel)
   at BTD_Mod_Helper.Api.Towers.ModTower.Register()
   at BTD_Mod_Helper.Api.Internal.ModContentTask.Coroutine()+MoveNext()
[08:47:42.844] [BloonsTD6_Mod_Helper] Registering ModContent for Useful Utilities...

**Comment by SavageTheUnicorn** [comment]
is this an issue with 2.1.3? i fixed it for myself already. i prolly modified version 2.1.1 tho

**Comment by loks1234** [comment]
Hi, mod used first was 2.1.1 but tried again with 2.1.3. The issue still persists with the same error.

**Comment by EngiGaming-tf2** [comment]
Facts
